#!/bin/bash
echo "Content-type: text/html"
echo ""
echo "<html><head><title>Rebooting Zer0 DropBox"
echo "</title></head><body>"
echo "<h3>Rebooting Zer0 DropBox</h3>"
echo "<pre> $(reboot) </pre>"
echo "</body></html>"

