#!/bin/ash

echo "Content-type: text/html"
echo ""

if [ ! -f /www/cgi-bin/sword/wifi/mon.txt]; then

     echo "<script>alert(\"Wi-Fi- monitor mode not enabled on wlan0mon\")</script>
     exit
fi

echo "<html><head><title>airodump wlan0mon</title></head>"
echo "<body><h1>airodump</h1>"

airodump-ng wlan0mon -w /www/SWORD/logs/airodump/airodump.txt &

/www/cgi-bin/sword/wifi/dump-refresh

echo "</body></html>"
