#!/bin/ash

echo "Content-type: text/html"
echo ""
echo "<html><head><title>Network Sniffer</title></head>"
echo "<body>"
echo "<h2>Network Sniffer Stopped</h2>"
echo "<pre>$(killall -9 tcpdump)</pre>"
echo "<pre>$(killall -9 tail)</pre>"
echo "</body>"
echo "</html>"
