#!/bin/bash
echo "Content-type: text/html"
echo ""
echo "<html><head><title>Bash as CGI"
echo "</title></head><body>"
echo "<h2>Network Sinffer Started</h2>"
a=$(ifconfig | grep 'inet addr:'| grep -v '127.0.0.1' | cut -d: -f2 | awk '{ print $1}' | cut -d. -f1)
b=$(ifconfig | grep 'inet addr:'| grep -v '127.0.0.1' | cut -d: -f2 | awk '{ print $1}' | cut -d. -f2)
c=$(ifconfig | grep 'inet addr:'| grep -v '127.0.0.1' | cut -d: -f2 | awk '{ print $1}' | cut -d. -f3)



date=$(date +"%d-%m-%y")
date2=$(date +"%H-%M")



echo "<pre>$(tcpdump -i br-lan -w /www/cgi-bin/sword/network/tcpdump/$date2-$date.pcap net $a.$b.$c.0/24)</pre>" ; #>> /www/cgi-bin/sword/network/tcpdump/tmp.txt


#tcpdump -i br-lan -w $date2-$date.pcap -n net .0/24